drop database h8;
create database h8;

\c h8

CREATE TABLE CUSTOMER (
	Cid INT,	
	Fname VARCHAR(15) NOT NULL,
	Lname VARCHAR(15) NOT NULL, 
	CAddress VARCHAR(200) NOT NULL,
	Cphone VARCHAR(12) NOT NULL UNIQUE,
	Email VARCHAR(30) UNIQUE,
	PRIMARY KEY (Cid)
);

CREATE TABLE DELIVERY_PERSON (
	Did INT,	
	Dfname VARCHAR(15) NOT NULL,
	Dlname VARCHAR(15) NOT NULL, 
	Dphone VARCHAR(12) NOT NULL UNIQUE,
	Vaccine_status BOOLEAN NOT NULL,
	Temp NUMERIC(5, 2) NOT NULL,
	Drating NUMERIC(2, 1),
	Dlocation VARCHAR(200) NOT NULL,
	PRIMARY KEY (Did)   
);

CREATE TABLE COUPON (
	Code VARCHAR(12),	
	Maxdisc INT NOT NULL,
	Exp_date TIMESTAMP NOT NULL,
	Minord INT NOT NULL,
	PRIMARY KEY (Code)   
);

CREATE TABLE TRANSACTION_ (
	Tid INT,	
	Tamount FLOAT NOT NULL,
	Mode VARCHAR(12) NOT NULL,
	PRIMARY KEY (Tid)   
);

CREATE TABLE RESTAURANT (
	Rid INT,	
	Rname VARCHAR(30) NOT NULL ,
	Rphone VARCHAR(12) NOT  NULL UNIQUE,
	Raddress VARCHAR(200) NOT NULL UNIQUE,
	Cuisine VARCHAR(20) NOT NULL,
	Rating NUMERIC(2, 1),
	Main_rid INT,
	PRIMARY KEY (Rid),    
	FOREIGN KEY (Main_rid) REFERENCES RESTAURANT(Rid)
);

CREATE TABLE MENU (
	Dishname VARCHAR(100) NOT NULL,
	Mrid INT,
	Mprice FLOAT NOT NULL,
	Type_ VARCHAR(12),
	Description_ VARCHAR(150),
	PRIMARY KEY (Dishname, Mrid),
	FOREIGN KEY (Mrid) REFERENCES RESTAURANT(Rid)
);

CREATE TABLE ORDER_ (
	Oid_ INT,
	Odid INT,
	Orid INT,
	PRIMARY KEY (Oid_),
	FOREIGN KEY (Odid) REFERENCES DELIVERY_PERSON(Did),
	FOREIGN KEY (Orid) REFERENCES RESTAURANT(Rid)
);

CREATE TABLE  CART (
	Cart_id INT,
	Cart_cid INT,
	PRIMARY KEY(Cart_id),
	FOREIGN KEY (Cart_cid) REFERENCES CUSTOMER(Cid)
);

CREATE TABLE ITEMS (
	Iname VARCHAR(150),
	Iprice FLOAT,
	Ioid INT,
	PRIMARY KEY(Iname, Iprice, Ioid),
	FOREIGN KEY (Ioid) REFERENCES ORDER_(Oid_)
);

CREATE TABLE CITEMS (
	Ciname VARCHAR(150),
	Ciprice FLOAT,
	Ccart_id INT,
	PRIMARY KEY(Ciname, Ciprice, Ccart_id),
	FOREIGN KEY (Ccart_id) REFERENCES CART(Cart_id)
);

CREATE TABLE ORDERS(
	Oid_history INT,
	Ocid INT,
	PRIMARY KEY(Oid_history, Ocid),
	FOREIGN KEY (Ocid) REFERENCES CUSTOMER(Cid)
);

CREATE TABLE MAKES (
	Mcid INT,
	Moid INT,
	Mtid INT,
	Timestamp_ TIMESTAMP,
	PRIMARY KEY(Mcid, Moid, Mtid),
	FOREIGN KEY (Mcid) REFERENCES CUSTOMER(Cid),
	FOREIGN KEY (Moid) REFERENCES ORDER_(Oid_),
	FOREIGN KEY (Mtid) REFERENCES TRANSACTION_(Tid)
);

CREATE TABLE APPLIES_ON (
	Acid INT,
	Aoid INT,
	Acode VARCHAR(12),
	PRIMARY KEY (Acid, Aoid, Acode),
	FOREIGN KEY (Acid) REFERENCES CUSTOMER(Cid),
	FOREIGN KEY (Aoid) REFERENCES ORDER_(Oid_),
	FOREIGN KEY (Acode) REFERENCES COUPON(Code)
);
